title: "BICEP + ENN + FusionAlpha"
description: "Triple Pipeline Demo for Navigation Under Uncertainty"
theme: jekyll-theme-minimal

plugins:
  - jekyll-relative-links
  
relative_links:
  enabled: true
  collections: true

markdown: kramdown

include:
  - "*.html"
  - "*.js"
  - "*.css"